### ISSUE TITLE
./configure misses man/uk/Makefile.in

### ISSUE THREAD

**Issue by dilyanpalauzov** [shadow-maint/shadow#548] opened 2022-08-12 09:47 UTC
shadow-1.12/configure prints:
```
config.status: creating Makefile
config.status: creating po/Makefile.in
config.status: creating doc/Makefile
config.status: creating man/Makefile
config.status: creating man/config.xml
config.status: creating man/po/Makefile
config.status: creating man/cs/Makefile
config.status: creating man/da/Makefile
config.status: creating man/de/Makefile
config.status: creating man/es/Makefile
config.status: creating man/fi/Makefile
config.status: creating man/fr/Makefile
config.status: creating man/hu/Makefile
config.status: creating man/id/Makefile
config.status: creating man/it/Makefile
config.status: creating man/ja/Makefile
config.status: creating man/ko/Makefile
config.status: creating man/pl/Makefile
config.status: creating man/pt_BR/Makefile
config.status: creating man/ru/Makefile
config.status: creating man/sv/Makefile
config.status: creating man/tr/Makefile
config.status: error: cannot find input file: `man/uk/Makefile.in'
```

As a matter of fact man/Makefile.am contains: `SUBDIRS = po cs da de es fi fr hu id it ja ko pl pt_BR ru sv tr zh_CN zh_TW` (so no `uk`), while configure.ac has on line 723 `AC_CONFIG_FILES([man/uk/Makefile])`.

**Comment by jubalh** [comment] 2022-08-12 09:55
Please look through the bugs before opening a new one.
This is a duplicate of https://github.com/shadow-maint/shadow/issues/547

**Closed** 2022-08-12 10:01 UTC
