### ISSUE TITLE
weird command execution when changing password

### ISSUE THREAD

**Issue by 54m4n** [shadow-maint/shadow#518] opened 2022-04-23 16:49 UTC
https://github.com/shadow-maint/shadow/blob/9cdb5251b6c30487a7d935a1a7827f493249479d/src/passwd.c#L194

If 511+ characters given, the rest of the characters tries to execute as a command. For example when you give 511 character and after `&ls&whoami&ping${IFS}8.8.8.8` then all the three commands will run.
Internal field separator depends on the bash, but it works in zsh for example, and many many distribution.

This is because the '-1' value accepts unlimited password.

Proof, you can try:
**as root:**
```
adduser test
new password: 12345
su test
```
**as test user:**
```
passwd
current password: 12345
new password: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111&ls&whoami
confirm password: as above
```

then magic happens.

Tested on: 
Linux kali 5.15.0-kali3-amd64 # 1 SMP Debian 5.15.15-2kali1 (2022-01-31) x86_64 GNU/Linux

**Comment by hallyn** [comment] 2022-04-25 02:31
Wow, I'm not happy with this code.  The pass_max_len is only used to tell the user the max nchars.  But it does appear to use a safe STRFCPY to copy the getpass() result.  And glibc's getpass() at least looks sane.  So I'm still looking for the cause of this.

**Comment by hallyn** [comment] 2022-04-25 02:55
Oh, but most of the code i was looking at was #ifndef PAM.

**Comment by 54m4n** [comment] 2022-04-25 15:56
as a regular user, can you please clear my mind? :D was it a good hit? :)

**Comment by hallyn** [comment] 2022-04-25 17:13
I guess I'll build a proposed package update.

**Comment by hallyn** [comment] 2022-04-26 03:26
> as a regular user, can you please clear my mind? :D was it a good hit? :)

I'm not sure I'm parsing this correctly, but if you mean is it a legit issue and a good find - yes, it is.

**Comment by 54m4n** [comment] 2022-04-26 07:05
Yes Hallyn sorry for my english, that was the point ;)

**Comment by hallyn** [comment] 2022-04-27 01:39
> I guess I'll build a proposed package update.

Ok - per #ubuntu-devel, vorlon (the debian pkg maintainer) will push a new package with the fix, so I'm closing this issue.

**Closed by hallyn** 2022-04-27 01:39 UTC
