### ISSUE TITLE
shadow 4.9 build error

### ISSUE THREAD

**Issue by paledega** [shadow-maint/shadow#407] opened 2021-08-31 14:12 UTC
```shell
make  all-recursive
make[1]: Entering directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9'
Making all in libmisc
make[2]: Entering directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/libmisc'
  CC       addgrps.lo
  CC       age.lo
  CC       audit_help.lo
  CC       basename.lo
  CC       chkname.lo
  CC       chowndir.lo
  CC       chowntty.lo
  CC       cleanup.lo
  CC       cleanup_group.lo
  CC       cleanup_user.lo
  CC       console.lo
  CC       copydir.lo
  CC       entry.lo
  CC       env.lo
  CC       failure.lo
  CC       find_new_uid.lo
  CC       find_new_sub_gids.lo
  CC       find_new_sub_uids.lo
  CC       getdate.lo
  CC       find_new_gid.lo
  CC       getgr_nam_gid.lo
  CC       getrange.lo
  CC       gettime.lo
  CC       hushed.lo
  CC       idmapping.lo
  CC       isexpired.lo
  CC       limits.lo
  CC       list.lo
  CC       log.lo
  CC       loginprompt.lo
  CC       mail.lo
  CC       motd.lo
  CC       myname.lo
  CC       obscure.lo
  CC       pam_pass.lo
  CC       pam_pass_non_interactive.lo
  CC       prefix_flag.lo
  CC       pwd2spwd.lo
  CC       pwdcheck.lo
  CC       pwd_init.lo
  CC       remove_tree.lo
  CC       rlogin.lo
  CC       root_flag.lo
  CC       salt.lo
  CC       setugid.lo
  CC       setupenv.lo
  CC       shell.lo
  CC       strtoday.lo
  CC       sub.lo
  CC       sulog.lo
  CC       ttytype.lo
  CC       tz.lo
  CC       ulimit.lo
  CC       user_busy.lo
  CC       utmp.lo
  CC       valid.lo
  CC       xgetpwnam.lo
  CC       xgetpwuid.lo
  CC       xgetgrnam.lo
  CC       xgetgrgid.lo
  CC       xgetspnam.lo
  CC       xmalloc.lo
  CC       yesno.lo
  CC       btrfs.lo
  CCLD     libmisc.la
make[2]: Leaving directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/libmisc'
Making all in lib
make[2]: Entering directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/lib'
  CC       libshadow_la-commonio.lo
  CC       libshadow_la-encrypt.lo
  CC       libshadow_la-fields.lo
  CC       libshadow_la-fputsx.lo
  CC       libshadow_la-getdef.lo
  CC       libshadow_la-get_gid.lo
  CC       libshadow_la-getlong.lo
  CC       libshadow_la-get_pid.lo
  CC       libshadow_la-get_uid.lo
  CC       libshadow_la-getulong.lo
  CC       libshadow_la-groupio.lo
  CC       libshadow_la-groupmem.lo
  CC       libshadow_la-gshadow.lo
  CC       libshadow_la-lockpw.lo
  CC       libshadow_la-nss.lo
  CC       libshadow_la-sssd.lo
  CC       libshadow_la-port.lo
  CC       libshadow_la-pwmem.lo
  CC       libshadow_la-pwauth.lo
  CC       libshadow_la-pwio.lo
  CC       libshadow_la-nscd.lo
  CC       libshadow_la-run_part.lo
  CC       libshadow_la-subordinateio.lo
  CC       libshadow_la-selinux.lo
  CC       libshadow_la-semanage.lo
  CC       libshadow_la-sgetgrent.lo
  CC       libshadow_la-sgetpwent.lo
  CC       libshadow_la-sgetspent.lo
  CC       libshadow_la-sgroupio.lo
  CC       libshadow_la-shadow.lo
  CC       libshadow_la-shadowio.lo
  CC       libshadow_la-shadowmem.lo
  CC       libshadow_la-spawn.lo
  CC       libshadow_la-utent.lo
  CCLD     libshadow.la
make[2]: Leaving directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/lib'
Making all in libsubid
make[2]: Entering directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/libsubid'
  CC       api.lo
  CCLD     libsubid.la
make[2]: Leaving directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/libsubid'
Making all in src
make[2]: Entering directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/src'
  CC       groups.o
  CC       login.o
  CC       login_nopam.o
  CC       su.o
  CC       suauth.o
  CC       id.o
  CC       sulogin.o
  CC       list_subid_ranges-list_subid_ranges.o
  CC       get_subid_owners-get_subid_owners.o
  CC       new_subid_range-new_subid_range.o
  CC       free_subid_range-free_subid_range.o
  CC       check_subid_range-check_subid_range.o
  CC       nologin.o
  CC       faillog.o
  CC       lastlog.o
  CC       chage.o
  CC       chfn.o
  CC       chsh.o
  CC       expiry.o
  CC       gpasswd.o
  CC       newgrp.o
  CC       passwd.o
  CC       newgidmap.o
  CC       newuidmap.o
  CC       chgpasswd.o
  CC       chpasswd.o
  CC       groupadd.o
su.c: In function 'main':
su.c:1210:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1210 |                 argv[-1] = cp;
      |                          ^
  CC       groupdel.o
  CC       groupmems.o
  CC       groupmod.o
  CC       grpck.o
  CC       grpconv.o
  CC       grpunconv.o
  CC       logoutd.o
  CC       newusers.o
  CC       pwck.o
  CC       pwconv.o
  CC       pwunconv.o
  CC       useradd.o
  CC       userdel.o
  CC       usermod.o
  CC       vipw.o
  CCLD     groups
  CCLD     id
  CCLD     sulogin
  CCLD     list_subid_ranges
logoutd.c: In function 'main':
logoutd.c:253:25: warning: 'strcat' argument 2 declared attribute 'nonstring' [-Wstringop-overread]
  253 |                         strcat (tty_name, ut->ut_line);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/utmp.h:29,
                 from ../lib/prototypes.h:51,
                 from logoutd.c:42:
/usr/include/bits/utmp.h:62:8: note: argument 'ut_line' declared here
   62 |   char ut_line[UT_LINESIZE]
      |        ^~~~~~~
  CCLD     get_subid_owners
  CCLD     new_subid_range
useradd.c: In function 'get_defaults':
useradd.c:418:41: warning: passing argument 1 of 'gr_free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  418 |                                 gr_free(grp);
      |                                         ^~~
In file included from useradd.c:64:
../lib/prototypes.h:211:56: note: expected 'struct group *' but argument is of type 'const struct group *'
  211 | extern void gr_free (/*@out@*/ /*@only@*/struct group *grent);
      |                                          ~~~~~~~~~~~~~~^~~~~
  CCLD     free_subid_range
  CCLD     check_subid_range
  CCLD     nologin
  CCLD     faillog
  CCLD     lastlog
usermod.c: In function 'process_flags':
usermod.c:1159:42: warning: passing argument 1 of 'gr_free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 1159 |                                 gr_free (grp);
      |                                          ^~~
In file included from usermod.c:61:
../lib/prototypes.h:211:56: note: expected 'struct group *' but argument is of type 'const struct group *'
  211 | extern void gr_free (/*@out@*/ /*@only@*/struct group *grent);
      |                                          ~~~~~~~~~~~~~~^~~~~
  CCLD     chage
  CCLD     chfn
  CCLD     chsh
  CCLD     expiry
  CCLD     gpasswd
  CCLD     newgrp
  CCLD     passwd
  CCLD     newgidmap
  CCLD     newuidmap
  CCLD     chgpasswd
  CCLD     chpasswd
  CCLD     groupadd
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_strerror'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_start'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `misc_conv'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_end'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_chauthtok'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_strerror'
collect2: error: ld returned 1 exit status
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_start'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `misc_conv'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_end'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_chauthtok'
  CCLD     groupdel
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1036: get_subid_owners] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1084: list_subid_ranges] Error 1
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_strerror'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_start'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `misc_conv'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_end'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_chauthtok'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1096: new_subid_range] Error 1
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_strerror'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_start'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `misc_conv'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_end'
/usr/bin/ld: ../libsubid/.libs/libsubid.so: undefined reference to `pam_chauthtok'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1032: free_subid_range] Error 1
make[2]: Leaving directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9/src'
make[1]: *** [Makefile:449: all-recursive] Error 1
make[1]: Leaving directory '/tmp/inary/shadow-4.9-1/work/shadow-4.9'
make: *** [Makefile:377: all] Error 2
```

**Comment by paledega** [comment] 2021-08-31 14:13
Compile args and command
```shell
./configure --prefix=/usr --with-libpam
make -j24
```

**Comment by jubalh** [comment] 2021-08-31 18:31
Looks like a duplicate of https://github.com/shadow-maint/shadow/issues/384.

**Comment by Apteryks** [comment] 2021-12-18 07:02
Worked for me; I choose to patch Makefile.in directly.

**Comment by hallyn** [comment] 2021-12-19 17:27
Thanks.

**Closed** 2021-12-19 17:26 UTC
