### ISSUE TITLE
Backup (or alternative source) of shadow-4.2.1.tar.xz

### ISSUE THREAD

**Issue by oimaasi** [shadow-maint/shadow#145] opened 2018-12-27 16:32 UTC
I am trying to make a build of cross linux from scratch according to the guide by https://github.com/repk/muslpi, and need the source of shadow-4.2.1 which was originally hosted under http://pkg-shadow.alioth.debian.org/releases/shadow-4.2.1.tar.xz. 

The site is down, and I can't seem to find any alternative source or backup of it. I downloaded the 4.2.1 source from your site, but judging from the patch file from muslpi, these two 4.2.1 sources are different.

Do you have any ideas where could I get the original shadow-4.2.1 source on pkg-shadow.alioth.debian.org? Thank you!

**Comment by glensc** [comment] 2018-12-28 10:06
refs:
- https://github.com/shadow-maint/shadow/issues/114#issuecomment-398401782
- https://github.com/shadow-maint/shadow/issues/115#issuecomment-397646648

duplicate of #115

**Closed** 2018-12-28 21:40 UTC
